-- 1. Create tables
CREATE TABLE role (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  name varchar(255) NOT NULL UNIQUE,
  PRIMARY KEY (id)
);

CREATE TABLE users (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  active boolean NOT NULL,
  is_banned boolean NOT NULL,
  business_type varchar(255) DEFAULT NULL,
  created_at timestamp(6) DEFAULT NULL,
  email varchar(100) NOT NULL,
  first_name varchar(50) DEFAULT NULL,
  image_url varchar(255) DEFAULT NULL,
  last_name varchar(50) DEFAULT NULL,
  oauth_provider varchar(255) DEFAULT NULL,
  oauth_provider_id varchar(255) DEFAULT NULL,
  password varchar(255) DEFAULT NULL,
  phone varchar(15) DEFAULT NULL,
  shop_description varchar(255) DEFAULT NULL,
  shop_name varchar(255) DEFAULT NULL,
  website varchar(255) DEFAULT NULL,
  role_id bigint DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT UK_users_email UNIQUE (email)
);

CREATE TABLE address (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  district varchar(50) DEFAULT NULL,
  full_name varchar(50) DEFAULT NULL,
  note varchar(100) DEFAULT NULL,
  phone_number varchar(15) DEFAULT NULL,
  province varchar(100) DEFAULT NULL,
  street varchar(50) DEFAULT NULL,
  ward varchar(50) DEFAULT NULL,
  user_id bigint NOT NULL,
  PRIMARY KEY (id)
);

-- 2. Add foreign keys
ALTER TABLE users ADD CONSTRAINT FK_users_role FOREIGN KEY (role_id) REFERENCES role(id);
ALTER TABLE address ADD CONSTRAINT FK_address_user FOREIGN KEY (user_id) REFERENCES users(id);

-- 3. Seed data
INSERT INTO role (id, name) OVERRIDING SYSTEM VALUE VALUES 
(1,'ADMIN'),
(2,'CUSTOMER');

INSERT INTO users (id, active, is_banned, business_type, created_at, email, first_name, image_url, last_name, oauth_provider, oauth_provider_id, password, phone, shop_description, shop_name, website, role_id) OVERRIDING SYSTEM VALUE VALUES 
(1,true,false,NULL,'2025-06-03 12:22:34.963615','admin@gmail.com','Admin',NULL,'User',NULL,NULL,'$2a$10$XImHvDQ3vUx2nibLZQaWQOuI9GxOPMhTL1RUio9ppxlVGf6TLkxea',NULL,NULL,NULL,NULL,1),
(2,true,false,NULL,'2025-06-03 12:22:35.063939','customer1@example.com','Customer',NULL,'One',NULL,NULL,'$2a$10$XImHvDQ3vUx2nibLZQaWQOuI9GxOPMhTL1RUio9ppxlVGf6TLkxea','0911111111',NULL,NULL,NULL,2),
(3,true,false,NULL,'2025-06-03 12:22:35.156950','customer2@example.com','Customer',NULL,'Two',NULL,NULL,'$2a$10$XImHvDQ3vUx2nibLZQaWQOuI9GxOPMhTL1RUio9ppxlVGf6TLkxea','0922222222',NULL,NULL,NULL,2),
(4,true,false,NULL,'2025-06-03 12:22:35.235213','customer3@example.com','Customer',NULL,'Three',NULL,NULL,'$2a$10$XImHvDQ3vUx2nibLZQaWQOuI9GxOPMhTL1RUio9ppxlVGf6TLkxea','0987654321',NULL,NULL,NULL,2),
(5,true,false,NULL,'2025-06-03 12:22:35.315256','customer4@example.com','Customer',NULL,'Four',NULL,NULL,'$2a$10$XImHvDQ3vUx2nibLZQaWQOuI9GxOPMhTL1RUio9ppxlVGf6TLkxea','0987654322',NULL,NULL,NULL,2),
(6,true,false,NULL,'2025-06-03 12:22:35.394107','customer5@example.com','Customer',NULL,'Five',NULL,NULL,'$2a$10$XImHvDQ3vUx2nibLZQaWQOuI9GxOPMhTL1RUio9ppxlVGf6TLkxea','0987654323',NULL,NULL,NULL,2),
(7,true,false,NULL,'2025-06-03 12:22:35.471975','customer6@example.com','Customer',NULL,'Six',NULL,NULL,'$2a$10$XImHvDQ3vUx2nibLZQaWQOuI9GxOPMhTL1RUio9ppxlVGf6TLkxea','0987654324',NULL,NULL,NULL,2),
(8,true,false,NULL,'2025-06-03 12:28:40.478519','customer@gmail.com','Customer',NULL,'User',NULL,NULL,'$2a$10$XImHvDQ3vUx2nibLZQaWQOuI9GxOPMhTL1RUio9ppxlVGf6TLkxea','0976543210',NULL,NULL,NULL,2),
(9,true,false,NULL,'2025-06-03 14:17:44.326548','customer7@example.com','Customer',NULL,'Seven',NULL,NULL,'$2a$10$XImHvDQ3vUx2nibLZQaWQOuI9GxOPMhTL1RUio9ppxlVGf6TLkxea','0922222222',NULL,NULL,NULL,2),
(15,true,false,NULL,'2025-06-13 19:09:47.608917','admin2@gmail.com','Admin',NULL,'System',NULL,NULL,'$2a$10$XImHvDQ3vUx2nibLZQaWQOuI9GxOPMhTL1RUio9ppxlVGf6TLkxea',NULL,NULL,NULL,NULL,1);

INSERT INTO address (id, district, full_name, note, phone_number, province, street, ward, user_id) OVERRIDING SYSTEM VALUE VALUES 
(1,'Thành phố Bắc Giang','Customer User','','0379641598','Tỉnh Bắc Giang','0x570d81A459Ad17B9B297Fc1592Efda6B55A715e3','Phường Tân Tiến',8),
(2,'Huyện Châu Thành','Customer User','','+1 6562294949','Tỉnh Tiền Giang','0x570d81A459Ad17B9B297Fc1592Efda6B55A715e3','Xã Kim Sơn',8),
(3,'Thị xã Nghĩa Lộ','Customer User','','0379641598','Tỉnh Yên Bái','0x570d81A459Ad17B9B297Fc1592Efda6B55A715e3','Xã Thanh Lương',8),
(4,'Huyện Phú Lương','Customer User','','0379641598','Tỉnh Thái Nguyên','0x570d81A459Ad17B9B297Fc1592Efda6B55A715e3','Xã Tức Tranh',8);

-- 4. Adjust identity sequences
SELECT setval(pg_get_serial_sequence('role', 'id'), coalesce(max(id), 1)) FROM role;
SELECT setval(pg_get_serial_sequence('users', 'id'), coalesce(max(id), 1)) FROM users;
SELECT setval(pg_get_serial_sequence('address', 'id'), coalesce(max(id), 1)) FROM address;
