-- Order Service owns orders and their immutable checkout snapshots.
-- Cart state belongs to Cart Service (Redis); payment transactions belong to Payment Service.

CREATE TABLE order_address (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  full_name varchar(255) DEFAULT NULL,
  province varchar(255) DEFAULT NULL,
  district varchar(255) DEFAULT NULL,
  ward varchar(255) DEFAULT NULL,
  street varchar(255) DEFAULT NULL,
  note varchar(255) DEFAULT NULL,
  phone_number varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  delivery_date timestamp(6) DEFAULT NULL,
  discount bigint DEFAULT NULL,
  order_date timestamp(6) DEFAULT NULL,
  order_status varchar(255) DEFAULT NULL,
  original_price bigint DEFAULT NULL,
  payment_method varchar(255) DEFAULT 'COD',
  payment_status varchar(255) DEFAULT NULL,
  total_discounted_price bigint DEFAULT NULL,
  total_items int DEFAULT NULL,
  order_address bigint DEFAULT NULL,
  user_id bigint NOT NULL,
  user_email varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE order_item (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  delivery_date timestamp(6) DEFAULT NULL,
  discount_percent int DEFAULT NULL,
  discounted_price bigint DEFAULT NULL,
  price bigint DEFAULT NULL,
  quantity int DEFAULT NULL,
  variant_name varchar(255) DEFAULT NULL,
  order_id bigint NOT NULL,
  product_id bigint NOT NULL,
  variant_id bigint NOT NULL,
  sku varchar(100) NOT NULL,
  product_name varchar(255) DEFAULT NULL,
  product_image_url varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
);

ALTER TABLE order_item
  ADD CONSTRAINT FK_order_item_order FOREIGN KEY (order_id) REFERENCES orders(id);
ALTER TABLE orders
  ADD CONSTRAINT FK_orders_order_address FOREIGN KEY (order_address) REFERENCES order_address(id);
