-- 1. Create tables
CREATE TABLE cart (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  discount int DEFAULT NULL,
  original_price int DEFAULT NULL,
  total_amount decimal(19,2) DEFAULT NULL,
  total_discounted_price int DEFAULT NULL,
  total_items int DEFAULT NULL,
  user_id bigint DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT UK_9emlp6m95v5er2bcqkjsw48he UNIQUE (user_id)
);

CREATE TABLE cart_item (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  discount_percent int DEFAULT NULL,
  discounted_price int DEFAULT NULL,
  price int DEFAULT NULL,
  quantity int NOT NULL,
  size varchar(255) DEFAULT NULL,
  cart_id bigint NOT NULL,
  product_id bigint NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  delivery_date timestamp(6) DEFAULT NULL,
  discount int DEFAULT NULL,
  order_date timestamp(6) DEFAULT NULL,
  order_status varchar(255) DEFAULT NULL,
  original_price int DEFAULT NULL,
  payment_method varchar(255) DEFAULT 'COD',
  payment_status varchar(255) DEFAULT NULL,
  total_discounted_price int DEFAULT NULL,
  total_items int DEFAULT NULL,
  order_address bigint DEFAULT NULL,
  user_id bigint NOT NULL,
  user_email varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE order_address (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  full_name varchar(255) DEFAULT NULL,
  province varchar(255) DEFAULT NULL,
  district varchar(255) DEFAULT NULL,
  ward varchar(255) DEFAULT NULL,
  street varchar(255) DEFAULT NULL,
  note varchar(255) DEFAULT NULL,
  phone_number varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE order_item (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  delivery_date timestamp(6) DEFAULT NULL,
  discount_percent int DEFAULT NULL,
  discounted_price int DEFAULT NULL,
  price int DEFAULT NULL,
  quantity int DEFAULT NULL,
  size varchar(255) DEFAULT NULL,
  order_id bigint NOT NULL,
  product_id bigint NOT NULL,
  product_name varchar(255) DEFAULT NULL,
  product_image_url varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE payment_details (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp(6) DEFAULT NULL,
  payment_date timestamp(6) DEFAULT NULL,
  payment_log text,
  payment_method varchar(255) DEFAULT NULL,
  payment_status varchar(255) DEFAULT NULL,
  total_amount int DEFAULT NULL,
  transaction_id varchar(100) DEFAULT NULL,
  updated_at timestamp(6) DEFAULT NULL,
  vnp_response_code varchar(255) DEFAULT NULL,
  vnp_secure_hash varchar(255) DEFAULT NULL,
  order_id bigint DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT UK_payment_details_order UNIQUE (order_id)
);

-- 2. Add foreign keys
ALTER TABLE cart_item ADD CONSTRAINT FK_cart_item_cart FOREIGN KEY (cart_id) REFERENCES cart(id);
ALTER TABLE order_item ADD CONSTRAINT FK_order_item_order FOREIGN KEY (order_id) REFERENCES orders(id);
ALTER TABLE orders ADD CONSTRAINT FK_orders_order_address FOREIGN KEY (order_address) REFERENCES order_address(id);
ALTER TABLE payment_details ADD CONSTRAINT FK_payment_details_order FOREIGN KEY (order_id) REFERENCES orders(id);

-- 3. Seed data
INSERT INTO order_address (id, full_name, province, district, ward, street, note, phone_number) OVERRIDING SYSTEM VALUE VALUES
(1, 'Nguyen Van A', 'Hanoi', 'Cau Giay', 'Dich Vong', '123 Xuan Thuy', 'Giao gio hanh chinh', '0987654321'),
(2, 'Tran Thi B', 'Ho Chi Minh', 'District 1', 'Ben Nghe', '456 Nguyen Hue', 'Call before delivery', '0912345678');
INSERT INTO cart (id, discount, original_price, total_amount, total_discounted_price, total_items, user_id) OVERRIDING SYSTEM VALUE VALUES 
(1,0,0,NULL,0,0,8),
(2,0,0,NULL,0,0,1),
(4,0,0,NULL,0,0,4);

INSERT INTO orders (id, delivery_date, discount, order_date, order_status, original_price, payment_method, payment_status, total_discounted_price, total_items, order_address, user_id) OVERRIDING SYSTEM VALUE VALUES
(1,NULL,608130,'2025-06-03 12:38:57.426821','CANCELLED',2097000,'VNPAY','CANCELLED',1488870,3,1,8),
(2,NULL,306900,'2025-06-03 12:40:59.401906','CONFIRMED',2790000,'VNPAY','PENDING',2483100,1,1,8),
(3,NULL,303920,'2025-06-03 12:50:23.859080','PENDING',3799000,'COD','PENDING',3495080,1,1,8),
(4,NULL,3078600,'2025-06-03 12:54:44.045739','PENDING',21990000,'COD','PENDING',18911400,1,1,8),
(5,NULL,3078600,'2025-06-03 13:07:49.756232','CANCELLED',21990000,'VNPAY','REFUNDED',18911400,1,1,8),
(6,NULL,2969100,'2025-06-03 13:08:09.229667','PENDING',32990000,'VNPAY','COMPLETED',30020900,1,1,8),
(7,NULL,3078600,'2025-06-03 13:25:43.413369','PENDING',21990000,'COD','PENDING',18911400,1,1,8),
(8,NULL,607840,'2025-06-03 13:30:03.516196','PENDING',7598000,'COD','PENDING',6990160,2,1,8),
(9,NULL,3078600,'2025-06-03 13:39:46.018112','PENDING',21990000,'COD','PENDING',18911400,1,1,8),
(10,NULL,1528300,'2025-06-03 13:40:42.258430','PENDING',8990000,'VNPAY','COMPLETED',7461700,1,1,8),
(11,NULL,2938600,'2025-06-03 14:32:52.380403','PENDING',20990000,'VNPAY','PENDING',18051400,1,1,8),
(12,NULL,499000,'2025-06-03 14:33:42.362239','PENDING',4990000,'VNPAY','PENDING',4491000,1,1,8),
(13,NULL,3078600,'2025-06-03 14:35:02.542877','PENDING',21990000,'VNPAY','PENDING',18911400,1,1,8),
(14,NULL,9798600,'2025-06-03 14:46:31.762749','PENDING',69990000,'VNPAY','PENDING',60191400,1,1,8),
(15,NULL,9798600,'2025-06-03 15:26:46.891677','PENDING',69990000,'COD','PENDING',60191400,1,1,8),
(16,NULL,19597200,'2025-06-03 16:12:55.603330','PENDING',139980000,'COD','PENDING',120382800,2,1,8),
(17,NULL,3078600,'2025-06-03 16:12:55.607247','PENDING',21990000,'COD','PENDING',18911400,1,1,8),
(18,NULL,29395800,'2025-06-04 01:05:23.253174','PENDING',209970000,'COD','PENDING',180574200,3,2,8),
(19,NULL,1528300,'2025-06-04 01:07:15.007279','PENDING',8990000,'COD','PENDING',7461700,1,1,8),
(20,'2025-06-04 01:11:42.347778',3078600,'2025-06-04 01:09:20.711773','DELIVERED',21990000,'COD','COMPLETED',18911400,1,1,8),
(21,NULL,2988700,'2025-06-04 02:02:06.767594','PENDING',22990000,'VNPAY','PENDING',20001300,1,1,8),
(22,NULL,303810,'2025-06-04 08:15:36.768772','PENDING',1599000,'VNPAY','COMPLETED',1295190,1,1,8),
(23,NULL,202710,'2025-06-04 08:40:44.415654','PENDING',699000,'COD','PENDING',496290,1,1,8);

INSERT INTO order_item (id, delivery_date, discount_percent, discounted_price, price, quantity, size, order_id, product_id) OVERRIDING SYSTEM VALUE VALUES 
(1,'2025-06-10 12:38:57.430716',29,496290,699000,3,'10000mAh',1,9),
(2,'2025-06-10 12:40:59.408498',11,2483100,2790000,1,'Standard',2,18),
(3,'2025-06-10 12:50:23.860746',8,3495080,3799000,1,'i7/16GB/1TB SSD',3,7),
(4,'2025-06-10 12:54:44.048275',14,18911400,21990000,1,'i7/16GB/1TB SSD/RTX 3050Ti',4,4),
(5,'2025-06-10 13:07:49.758305',14,18911400,21990000,1,'i7/16GB/1TB SSD/RTX 3050Ti',5,4),
(6,'2025-06-10 13:08:09.232315',9,30020900,32990000,1,'i7/16GB/1TB SSD',6,6),
(7,'2025-06-10 13:25:43.414681',14,18911400,21990000,1,'i7/16GB/1TB SSD/RTX 3050Ti',7,4),
(8,'2025-06-10 13:30:03.516196',8,3495080,3799000,2,'i7/16GB/1TB SSD',8,7),
(9,'2025-06-10 13:39:46.019526',14,18911400,21990000,1,'i7/16GB/1TB SSD/RTX 3050Ti',9,4),
(10,'2025-06-10 13:40:42.259844',17,7461700,8990000,1,'Một cỡ',10,10),
(11,'2025-06-10 14:32:52.386746',14,18051400,20990000,1,'256GB',11,3),
(12,'2025-06-10 14:33:42.364551',10,4491000,4990000,1,'ISO',12,21),
(13,'2025-06-10 14:35:02.545639',14,18911400,21990000,1,'i7/16GB/1TB SSD/RTX 3050Ti',13,4),
(14,'2025-06-10 14:46:31.764797',14,60191400,69990000,1,'Ryzen 7/16GB/1TB SSD/RTX 4080',14,5),
(15,'2025-06-10 15:26:46.900504',14,60191400,69990000,1,'Ryzen 7/16GB/1TB SSD/RTX 4080',15,5),
(16,'2025-06-10 16:12:55.605116',14,60191400,69990000,2,'Ryzen 9/32GB/2TB SSD/RTX 4090',16,5),
(17,'2025-06-10 16:12:55.608503',14,18911400,21990000,1,'i7/16GB/1TB SSD/RTX 3050Ti',17,4),
(18,'2025-06-11 01:05:23.267578',14,60191400,69990000,3,'Ryzen 7/16GB/1TB SSD/RTX 4080',18,5),
(19,'2025-06-11 01:07:15.009255',17,7461700,8990000,1,'Một cỡ',19,10),
(20,'2025-06-11 01:09:20.713368',14,18911400,21990000,1,'i7/16GB/1TB SSD/RTX 3050Ti',20,4),
(21,'2025-06-11 02:02:06.771290',13,20001300,22990000,1,'256GB',21,2),
(22,'2025-06-11 08:15:36.777392',19,1295190,1599000,1,'19200mAh',22,8),
(23,'2025-06-11 08:40:44.422917',29,496290,699000,1,'20000mAh',23,9);

INSERT INTO payment_details (id, created_at, payment_date, payment_log, payment_method, payment_status, total_amount, transaction_id, updated_at, vnp_response_code, vnp_secure_hash, order_id) OVERRIDING SYSTEM VALUE VALUES 
(1,'2025-06-03 12:39:29.974150',NULL,NULL,'VNPAY','PENDING',1488870,'1_62906712','2025-06-03 12:39:29.974153',NULL,'3d4a7c1f137fe2485467cf4dedcc83065621e031ec93b76348cc657c620357608c86b1a528d45368b0a6654bed3d4aa8ce583b27f433afc7e3f2991b4cc1cef9',1),
(13,'2025-06-03 15:18:39.152960','2025-06-03 15:21:45.817229','{"vnp_Amount":"1891140000","vnp_BankCode":"NCB","vnp_BankTranNo":"VNP14996854","vnp_CardType":"ATM","vnp_OrderInfo":"Thanh toan don hang #5","vnp_PayDate":"20250603151939","vnp_ResponseCode":"00","vnp_TmnCode":"N7MGBPT4","vnp_TransactionNo":"14996854","vnp_TransactionStatus":"00","vnp_TxnRef":"5_96814198","vnp_SecureHash":"668e5485ced7ef18ca10d20379f20c29baa6661fecaac2af409e0e4a20e0de5c3f5d1b262fd9dacaf158506a6ae004d8aea7cac2722f64d18029b601af4dd1fd"}','VNPAY','COMPLETED',18911400,'5_96814198','2025-06-03 15:21:45.817919','00','7b095a5ec094f4daa903453eeb7df9bfbeab37b9e6d896aa5a28f57f3b46c8822d2391501a4cc8439940afbba13b64b6b4a51335ef438d980de82b1dc110899f',5),
(14,'2025-06-03 15:21:50.350584','2025-06-03 15:22:27.739967','{"step":"4","vnp_Amount":"3002090000","vnp_BankCode":"NCB","vnp_BankTranNo":"VNP14996867","vnp_CardType":"ATM","vnp_OrderInfo":"Thanh toan don hang #6","vnp_PayDate":"20250603152255","vnp_ResponseCode":"00","vnp_TmnCode":"N7MGBPT4","vnp_TransactionNo":"14996867","vnp_TransactionStatus":"00","vnp_TxnRef":"6_94606853","vnp_SecureHash":"ae5e9aa9e42c17ce61a0e47bd653cc55b4edf95a20e195f9cfd81896eacced931f755007a10278fcd9d61cf4a207e6c90ca82d643de671123e588535bbec8759"}','VNPAY','COMPLETED',30020900,'6_94606853','2025-06-03 15:22:27.740792','00','6d22d3b3351e1a35942506cff0dd40f4d9dd3b7ca6c62923f46969d66c591d9012c579e49ea4ad9ed31e5883613281c2128981785f7c5e042479991e3f8280b0',6),
(15,'2025-06-04 02:02:06.828998',NULL,NULL,'VNPAY','PENDING',20001300,'21_01302998','2025-06-04 02:02:06.829018',NULL,'3f8075a92a215a3f2f3b5c304582e087420db58c021215f4c6ca33fb734994e361f736282823a9ecf4264f215670ed916e4be0fe8ba82f31c10419a9ebe9e021',21),
(16,'2025-06-04 08:15:36.866384','2025-06-04 08:16:02.389191','{"step":"4","vnp_Amount":"129519000","vnp_BankCode":"NCB","vnp_BankTranNo":"VNP14998145","vnp_CardType":"ATM","vnp_OrderInfo":"Thanh toan don hang #22","vnp_PayDate":"20250604081630","vnp_ResponseCode":"00","vnp_TmnCode":"N7MGBPT4","vnp_TransactionNo":"14998145","vnp_TransactionStatus":"00","vnp_TxnRef":"22_29308523","vnp_SecureHash":"fb897b2c0ae24f27c004fde96728ec2025d50f6868fd46e0bb6a7c4431de48bcaa0c2667b3e9cf6b67fa3d8e4dd5497a011b08cf05572639aff4404721b21082"}','VNPAY','COMPLETED',1295190,'22_29308523','2025-06-04 08:16:02.391145','00','9c6c8c1a6150bc40dfbf91d084b95f07db1a6bf1746d04a81f6bce94d88dba303eeec71acc03ae333933261d1d7f9a23c936b6f4543598da7a368f8f77f1a0de',22);

-- 4. Adjust identity sequences
SELECT setval(pg_get_serial_sequence('cart', 'id'), coalesce(max(id), 1)) FROM cart;
SELECT setval(pg_get_serial_sequence('cart_item', 'id'), coalesce(max(id), 1)) FROM cart_item;
SELECT setval(pg_get_serial_sequence('orders', 'id'), coalesce(max(id), 1)) FROM orders;
SELECT setval(pg_get_serial_sequence('order_item', 'id'), coalesce(max(id), 1)) FROM order_item;
SELECT setval(pg_get_serial_sequence('order_address', 'id'), coalesce(max(id), 1)) FROM order_address;
SELECT setval(pg_get_serial_sequence('payment_details', 'id'), coalesce(max(id), 1)) FROM payment_details;
