-- 1. Create tables
CREATE TABLE payment_details (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp(6) DEFAULT NULL,
  payment_date timestamp(6) DEFAULT NULL,
  payment_log text,
  payment_method varchar(255) DEFAULT NULL,
  payment_status varchar(255) DEFAULT NULL,
  total_amount bigint DEFAULT NULL,
  transaction_id varchar(100) DEFAULT NULL,
  updated_at timestamp(6) DEFAULT NULL,
  vnp_response_code varchar(255) DEFAULT NULL,
  vnp_secure_hash varchar(255) DEFAULT NULL,
  order_id bigint DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT UK_of2hvjrt3h42uja5aibie81tp UNIQUE (order_id)
);
