-- 1. Create tables
CREATE TABLE payment_details (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp(6) DEFAULT NULL,
  payment_date timestamp(6) DEFAULT NULL,
  payment_log text,
  payment_method varchar(255) DEFAULT NULL,
  payment_status varchar(255) DEFAULT NULL,
  total_amount bigint DEFAULT NULL,
  transaction_id varchar(100) DEFAULT NULL,
  updated_at timestamp(6) DEFAULT NULL,
  vnp_response_code varchar(255) DEFAULT NULL,
  vnp_secure_hash varchar(255) DEFAULT NULL,
  order_id bigint DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT UK_of2hvjrt3h42uja5aibie81tp UNIQUE (order_id)
);

-- 2. Seed data
INSERT INTO payment_details (id, created_at, payment_date, payment_log, payment_method, payment_status, total_amount, transaction_id, updated_at, vnp_response_code, vnp_secure_hash, order_id) OVERRIDING SYSTEM VALUE VALUES 
(1,'2025-06-03 12:39:29.974150',NULL,NULL,'VNPAY','PENDING',1488870,'1_62906712','2025-06-03 12:39:29.974153',NULL,'3d4a7c1f137fe2485467cf4dedcc83065621e031ec93b76348cc657c620357608c86b1a528d45368b0a6654bed3d4aa8ce583b27f433afc7e3f2991b4cc1cef9',1),
(13,'2025-06-03 15:18:39.152960','2025-06-03 15:21:45.817229','{"vnp_Amount":"1891140000","vnp_BankCode":"NCB","vnp_BankTranNo":"VNP14996854","vnp_CardType":"ATM","vnp_OrderInfo":"Thanh toan don hang #5","vnp_PayDate":"20250603151939","vnp_ResponseCode":"00","vnp_TmnCode":"N7MGBPT4","vnp_TransactionNo":"14996854","vnp_TransactionStatus":"00","vnp_TxnRef":"5_96814198","vnp_SecureHash":"668e5485ced7ef18ca10d20379f20c29baa6661fecaac2af409e0e4a20e0de5c3f5d1b262fd9dacaf158506a6ae004d8aea7cac2722f64d18029b601af4dd1fd"}','VNPAY','COMPLETED',18911400,'5_96814198','2025-06-03 15:21:45.817919','00','7b095a5ec094f4daa903453eeb7df9bfbeab37b9e6d896aa5a28f57f3b46c8822d2391501a4cc8439940afbba13b64b6b4a51335ef438d980de82b1dc110899f',5),
(14,'2025-06-03 15:21:50.350584','2025-06-03 15:22:27.739967','{"step":"4","vnp_Amount":"3002090000","vnp_BankCode":"NCB","vnp_BankTranNo":"VNP14996867","vnp_CardType":"ATM","vnp_OrderInfo":"Thanh toan don hang #6","vnp_PayDate":"20250603152255","vnp_ResponseCode":"00","vnp_TmnCode":"N7MGBPT4","vnp_TransactionNo":"14996867","vnp_TransactionStatus":"00","vnp_TxnRef":"6_94606853","vnp_SecureHash":"ae5e9aa9e42c17ce61a0e47bd653cc55b4edf95a20e195f9cfd81896eacced931f755007a10278fcd9d61cf4a207e6c90ca82d643de671123e588535bbec8759"}','VNPAY','COMPLETED',30020900,'6_94606853','2025-06-03 15:22:27.740792','00','6d22d3b3351e1a35942506cff0dd40f4d9dd3b7ca6c62923f46969d66c591d9012c579e49ea4ad9ed31e5883613281c2128981785f7c5e042479991e3f8280b0',6),
(15,'2025-06-04 02:02:06.828998',NULL,NULL,'VNPAY','PENDING',20001300,'21_01302998','2025-06-04 02:02:06.829018',NULL,'3f8075a92a215a3f2f3b5c304582e087420db58c021215f4c6ca33fb734994e361f736282823a9ecf4264f215670ed916e4be0fe8ba82f31c10419a9ebe9e021',21),
(16,'2025-06-04 08:15:36.866384','2025-06-04 08:16:02.389191','{"step":"4","vnp_Amount":"129519000","vnp_BankCode":"NCB","vnp_BankTranNo":"VNP14998145","vnp_CardType":"ATM","vnp_OrderInfo":"Thanh toan don hang #22","vnp_PayDate":"20250604081630","vnp_ResponseCode":"00","vnp_TmnCode":"N7MGBPT4","vnp_TransactionNo":"14998145","vnp_TransactionStatus":"00","vnp_TxnRef":"22_29308523","vnp_SecureHash":"fb897b2c0ae24f27c004fde96728ec2025d50f6868fd46e0bb6a7c4431de48bcaa0c2667b3e9cf6b67fa3d8e4dd5497a011b08cf05572639aff4404721b21082"}','VNPAY','COMPLETED',1295190,'22_29308523','2025-06-04 08:16:02.391145','00','9c6c8c1a6150bc40dfbf91d084b95f07db1a6bf1746d04a81f6bce94d88dba303eeec71acc03ae333933261d1d7f9a23c936b6f4543598da7a368f8f77f1a0de',22);

-- 3. Adjust identity sequences
SELECT setval(pg_get_serial_sequence('payment_details', 'id'), coalesce(max(id), 1)) FROM payment_details;
