server:
  port: 8082

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/kyro_catalog}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

cloudinary:
  cloudName: ${CLOUDINARY_CLOUD_NAME:mock_cloud}
  apiKey: ${CLOUDINARY_API_KEY:mock_key}
  apiSecret: ${CLOUDINARY_API_SECRET:mock_secret}
  apiSecure: ${CLOUDINARY_API_SECURE:true}
