server:
  port: 8084

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:duongtriphucpd@gmail.com}
    password: ${MAIL_PASSWORD:vpvvlqbqiotqnyvg}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
