CREATE TABLE carts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL UNIQUE,
  version bigint NOT NULL DEFAULT 0,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cart_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cart_id bigint NOT NULL REFERENCES carts(id) ON DELETE CASCADE,
  product_id bigint NOT NULL,
  variant_id bigint NOT NULL,
  product_name varchar(255) NOT NULL,
  sku varchar(100) NOT NULL,
  variant_name varchar(255) NOT NULL,
  product_image_url varchar(255),
  quantity integer NOT NULL CHECK (quantity > 0),
  price bigint NOT NULL CHECK (price >= 0),
  sale_price bigint NOT NULL CHECK (sale_price >= 0),
  discount_percent integer NOT NULL CHECK (discount_percent BETWEEN 0 AND 100),
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (cart_id, variant_id)
);

CREATE TABLE processed_cart_events (
  order_id bigint PRIMARY KEY,
  processed_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
