CREATE TABLE carts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL UNIQUE,
  version bigint NOT NULL DEFAULT 0,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cart_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cart_id bigint NOT NULL REFERENCES carts(id) ON DELETE CASCADE,
  product_id bigint NOT NULL,
  product_name varchar(255) NOT NULL,
  product_image_url varchar(255),
  quantity integer NOT NULL CHECK (quantity > 0),
  price integer NOT NULL,
  size varchar(255),
  discount_percent integer,
  discounted_price integer,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE NULLS NOT DISTINCT (cart_id, product_id, size)
);

CREATE TABLE processed_cart_events (
  order_id bigint PRIMARY KEY,
  processed_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
